package com.evcs.favorites.security

import com.evcs.favorites.data.routing.GoogleRoutesClient
import com.evcs.favorites.data.routing.RoutingDestination
import kotlinx.coroutines.runBlocking
import okhttp3.mockwebserver.MockResponse
import okhttp3.mockwebserver.MockWebServer
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import java.io.File

/**
 * Verification test for Phase 01: Core Security, Google Routes Package Alignment & Manifest Hardening.
 *
 * Validates:
 * 1. GoogleRoutesClient.ANDROID_PACKAGE_VALUE constant equals "com.evplus.app".
 * 2. HTTP requests generated by GoogleRoutesClient carry X-Android-Package: com.evplus.app.
 * 3. AndroidManifest.xml does not request ACCESS_BACKGROUND_LOCATION.
 * 4. firestore.rules exists in repository root and enforces request.auth.uid == userId.
 */
class SecurityAndPackageConfigAuditTest {

    private lateinit var mockServer: MockWebServer

    @Before
    fun setUp() {
        mockServer = MockWebServer()
        mockServer.start()
    }

    @After
    fun tearDown() {
        mockServer.shutdown()
    }

    private fun resolveFile(vararg candidatePaths: String): File {
        for (path in candidatePaths) {
            val file = File(path)
            if (file.exists()) return file
        }
        val userDir = System.getProperty("user.dir") ?: "."
        for (path in candidatePaths) {
            val file = File(userDir, path)
            if (file.exists()) return file
        }
        throw AssertionError("Could not find any file from candidates: ${candidatePaths.joinToString()} (user.dir=$userDir)")
    }

    @Test
    fun testGoogleRoutesClient_androidPackageAlignment() {
        // Criterion 1: Verify GoogleRoutesClient.ANDROID_PACKAGE_VALUE == "com.evplus.app"
        assertEquals("com.evplus.app", GoogleRoutesClient.ANDROID_PACKAGE_VALUE)
    }

    @Test
    fun testGoogleRoutesClient_dispatchesCorrectAndroidPackageHeader() = runBlocking {
        // Criterion 2: Verify X-Android-Package header generated in HTTP requests equals "com.evplus.app"
        val client = GoogleRoutesClient(baseUrl = mockServer.url("/").toString())

        mockServer.enqueue(
            MockResponse()
                .setResponseCode(200)
                .setHeader("Content-Type", "application/json")
                .setBody("[]")
        )

        val destinations = listOf(
            RoutingDestination(id = "station_test", latitude = 10.7780, longitude = 106.7020)
        )

        client.computeRouteMatrix(
            apiKey = "test_api_key",
            originLat = 10.7769,
            originLng = 106.7009,
            destinations = destinations
        )

        val recordedRequest = mockServer.takeRequest()
        assertEquals("com.evplus.app", recordedRequest.getHeader(GoogleRoutesClient.HEADER_ANDROID_PACKAGE))
        assertEquals("com.evplus.app", recordedRequest.getHeader("X-Android-Package"))
    }

    @Test
    fun testAndroidManifest_doesNotContainBackgroundLocationPermission() {
        // Criterion 3: Verify AndroidManifest.xml does NOT contain android.permission.ACCESS_BACKGROUND_LOCATION
        val manifestFile = resolveFile(
            "app/src/main/AndroidManifest.xml",
            "src/main/AndroidManifest.xml",
            "../app/src/main/AndroidManifest.xml"
        )
        assertTrue("AndroidManifest.xml must exist", manifestFile.exists())

        val manifestContent = manifestFile.readText()
        assertFalse(
            "AndroidManifest.xml must not request ACCESS_BACKGROUND_LOCATION",
            manifestContent.contains("android.permission.ACCESS_BACKGROUND_LOCATION")
        )
        // Ensure other required location permissions remain intact
        assertTrue(
            "AndroidManifest.xml must still contain ACCESS_FINE_LOCATION",
            manifestContent.contains("android.permission.ACCESS_FINE_LOCATION")
        )
        assertTrue(
            "AndroidManifest.xml must still contain ACCESS_COARSE_LOCATION",
            manifestContent.contains("android.permission.ACCESS_COARSE_LOCATION")
        )
    }

    @Test
    fun testFirestoreRules_existsAndEnforcesUserAuthorization() {
        // Criterion 4: Verify firestore.rules exists and contains correct pattern request.auth.uid == userId
        val firestoreRulesFile = resolveFile(
            "firestore.rules",
            "../firestore.rules"
        )
        assertTrue("firestore.rules must exist in root", firestoreRulesFile.exists())

        val rulesContent = firestoreRulesFile.readText()
        assertTrue(
            "firestore.rules must contain rules_version = '2'",
            rulesContent.contains("rules_version = '2'")
        )
        assertTrue(
            "firestore.rules must contain favorites path matcher",
            rulesContent.contains("match /users/{userId}/userdata/favorites")
        )
        assertTrue(
            "firestore.rules must enforce authentication and request.auth.uid == userId",
            rulesContent.contains("request.auth.uid == userId")
        )
    }
}
